some new functions to help playing with bias- and trigger-patches
fact-project/pyfact pull request #21
Opened 2016-11-17 09:26 UTC by dneise

We have twice as many bias-patches as trigger-patches in FACT, but their mapping in non trivial.
In addition when trying to combine the two "bias_patch_currents" in the one "trigger_patch_current" one needs even to know which of the two patches had 4 pixels and which had 5...

This all repeatedly kicked me in the balls so I thought it should go in here.

I also added some tests, but went crazy while writing them ... so this is not yet done, but I need it on newdaq, so I pushed it ... 

I guess the functions should not go into `fact.pixels` but somewhere else ... however implemplementing it there felt so natural, I couldn't resist.

Looking forward to your feedback.

2016-11-17 12:01 UTC, MaxNoe commented
This breaks python 3.3 compatibility (because pandas 0.18 require 3.4). I think we should drop the 3.3 test from travis.

2016-11-17 15:15 UTC, MaxNoe commented on fact/pixels.py
> +def take_apart_trigger_values_for_bias_patches(trigger_rates):
trigger_rates? This valid for every array of length 160, right? Isn't this simply converting `trigger_patch_id` -> `bias_patch_id` ?

Would jsut two conversion methods `trigger_patch_to_bias_patch` and `bias_patch_to_trigger_patch` be sufficient and more general?

2016-11-17 15:16 UTC, maxnoe requested changes

2016-11-17 15:16 UTC, MaxNoe commented on fact/pixels.py
> +def patch_indices():
I think functions should be verbs. `get_patch_indices` or `read_patch_indices`

2016-11-17 16:39 UTC, dneise commented
>> I think we should drop the 3.3 test from travis.
I think so too

2016-11-17 16:43 UTC, dneise commented on fact/pixels.py
> +def take_apart_trigger_values_for_bias_patches(trigger_rates):
I think, There is no general way to combine or take apart these values ... combining could be:
 * sum them,
 * sum them with weights 4/9 and 5/9 
 * take their max
 * ...

taking apart could be:
 * simply duplicate them, as I did there
 * divide by 2
 * divide into 4-ninth and 5-ninth
 * ...

2016-11-17 16:44 UTC, dneise commented on fact/pixels.py
> +def take_apart_trigger_values_for_bias_patches(trigger_rates):
I think before making stuff general ... let's just implement features we need .. then add more features ... and once we find some features have overlapping code, we refactor in order to increase code reuse ... let's not search for generality ... at least that's how I understood uncle bob.

2016-11-17 16:47 UTC, dneise commented on fact/pixels.py
> +def patch_indices():
I think this should not even be a function, but a module global variable like, `pixel_mapping`. What do you think?

2016-11-17 17:03 UTC, MaxNoe commented on fact/pixels.py
> +def take_apart_trigger_values_for_bias_patches(trigger_rates):
But you implemented a function that does the general id conversion AND something else. That's not uncle-bobish

2016-11-17 17:04 UTC, MaxNoe commented on fact/pixels.py
> +def pixel_dataframe():
This should either be a member or have another name (verb)

2016-11-17 19:19 UTC, maxnoe approved these changes

2016-11-17 19:20 UTC, MaxNoe commented
Now the tests are failing, I think you forgot to rename the functions in the tests

2016-11-18 12:07 UTC, MaxNoe commented
Looks good to me!

2016-11-18 12:07 UTC, merged