Write h5py
fact-project/pyfact pull request #39
Opened 2017-03-29 13:45 UTC by MaxNoe

This adds methods to write h5py style hdf5 files from pandas dataframes

2017-03-30 15:13 UTC, kbruegge approved these changes
Maybe not part of this PR. But I think we should make the `read_data` method also be able to read csv files using `pd.read_csv()`. Its quite convenient and doesn't add much  code.

2017-03-30 15:23 UTC, jebuss requested changes

2017-03-30 15:23 UTC, jebuss commented on fact/io.py
> +def write_data(df, file_path, key='table', hdf_format='pandas'):
doesn't a bool use_pandas make more sense?

2017-03-30 15:23 UTC, jebuss commented on fact/io.py
> +def write_data(df, file_path, key='table', hdf_format='pandas'):
can we you 'data' instead of 'table' as default key? I think its a little less general.

2017-03-30 15:34 UTC, MaxNoe commented on fact/io.py
> +def write_data(df, file_path, key='table', hdf_format='pandas'):
I don't really care about the default, data is fine with me.

2017-03-30 15:38 UTC, jebuss approved these changes

2017-03-30 15:43 UTC, MaxNoe commented
@mackaiver done

2017-03-30 15:49 UTC, merged

2017-03-31 07:30 UTC, dneise commented
I am missing some motivational information, as in context. 
What is this feature used for? 
Does this solve an issue?

I mean, technically this is all fine. It does not change API and I believe it is implemented well enough, as it has been reviewed. Also it is of use for a larger group of fact members, so putting it here for everybody to benefit from it also makes sense. 

Maybe a section in the README presenting this new feature to people *outside* TUDO would be good. Alternatively an issue, presenting the problem this feature is going to solve also serves as docu. Or simply a little bit of text in the comment section of this PR not about what ... but about the why would be good.